class onboard_answer:
    ans1 = "*1. Thủ tục onboard/tiếp nhận nhân viên mới như thế nào?*\nBạn vui lòng xem quy trình tiếp nhận nhân viên mới tại link dưới đây:\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=268|Quy trình onboard>"
    ans2 = "*2. Nhân viên Telio mới cần làm những thủ tục gì?*\nBạn vui lòng xem Video hướng dẫn các thủ tục cần làm cho các Telio-er mới gia nhập tại link dưới đây:\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=268|Video hướng dẫn thủ tục cần làm cho Telio - er mới gia nhập>"
    ans3 = "*3. Thông tin về email và tài khoản 1 office?*\nThông tin email và tài khoản 1 Office, Bộ phận Nhân sự đã gửi vào email cá nhân cho bạn khi gia nhập công ty. Bạn vui lòng kiểm tra lại thông tin, nếu có bất kỳ thắc mắc nào về tài khoản liên hệ:\nHN: Ms. Dương Tuyết (Email/Slack: tuyetduong@telio.vn)\nHCM: Ms. Nguyễn Thu (Email/Slack: nguyenthu1@telio.vn)"
    ans4 = "*4. Nếu có thắc mắc về chế độ chính sách thì liên hệ ai?*\nBạn vui lòng liên hệ bộ phận C&B theo thông tin dưới đây:\n1. Đặng Thị Thanh - Email/Slack: dangthanh@telio.vn\n2. Dương Thị Tuyết - Email/Slack: tuyetduong@telio.vn"
    ans5 = "*5. Bộ hồ sơ nhân sự bao gồm những gì?*\nBạn vui lòng nộp cho Phòng Nhân sự bộ hồ sơ cá nhân trước ngày 29 của tháng nhận việc, hồ sơ bao gồm:\n1. Sơ yếu lý lịch có xác nhận của chính quyền địa phương trong vòng 6 tháng trước ngày onboard\n2. CMND/CCCD photo công chứng\n3. Sổ hộ khẩu photo công chứng\n4. Bằng cấp photo công chứng\n5. Giấy khám sức khỏe xác nhận sớm nhất trong vòng 1 tháng trước ngày onboard\n6. Giấy xác nhận không tiền án tiền sự (Áp dụng với Giám sát giao hàng và phụ kho)"
    ans6 = "*6. Công ty thanh toán lương như thế nào?*\nCông ty chỉ trả lương qua thẻ Ngân hàng Quân đội MB Bank và không thanh toán tiền mặt. STK Ngân hàng CBNV tự mở và thông báo lại cho Bộ phận C&B qua email: hr@telio.vn"
    ans7 = "*7. Làm thế nào để tìm Số điện thoại và Email của đồng nghiệp?*\nBạn đăng nhập vào tài khoản 1 Office, vào mục Social, di chuột đến biểu tượng tìm kiếm trong bài viết, người dùng, gõ tên đồng nghiệp bạn muốn tìm thông tin, sau đó nhấn tìm kiếm. Sau đó giao hiện hiện ra họ tên của đồng nghiệp, bạn click vào tên đồng nghiệp cần tìm để xem thông tin số điện thoại và email."
    ans8 = "*8. Cách sử dụng slack như thế nào?*\nBạn vui lòng xem Hướng dẫn sử dụng Slack như link dưới đây.\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=268|Hướng dẫn sử dụng Slack>"

class quit_answer:
    ans1 = "*1. Thủ tục nghỉ việc như thế nào?*\nBạn vui lòng xem hướng dẫn thủ tục nghỉ việc tại link dưới đây:\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=274|Link: Hướng dẫn thủ tục nghỉ việc>"
    ans2 = "*2. Nếu nghỉ việc thì thời gian nhận khoản lương còn lại là khi nào?*\nTiền lương còn lại của bạn sẽ được thanh toán vào các kỳ ngày 5, 10, 25 hàng tháng nếu bạn hoàn thiện đủ thủ tục nghỉ việc (Đơn xin nghỉ việc + Biên bản bàn giao và hồ sơ cá nhân nếu chưa nộp đủ)"
    ans3 = "*3. Thủ tục hưởng Bảo hiểm thất nghiệp?*\nBạn vui lòng xem hướng dẫn về thủ tục hưởng Bảo hiểm thất nghiệp tại link dưới đây\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=274|Link: Hướng dẫn thủ tục nghỉ việc>"
    ans4 = "*4. Nghỉ việc có được thanh toán phép tồn khi nghỉ việc không?*\nCBNV sẽ được thanh toán phép tồn khi nghỉ việc"
    ans5 = "*5. Bao giờ được trả sổ BHXH đã chốt khi nghỉ việc?*\nSổ BHXH sẽ được trả muộn nhất trong vòng 30 ngày kể từ ngày nghỉ việc. Nếu bạn nộp sổ sau ngày nghỉ việc, bạn sẽ được trả sổ trong vòng 30 ngày kể từ ngày bộ phận C&B nhận sổ BHXH của bạn."

class move_answer:
    ans1 = "*1. Thủ tục điều chuyển nhân sự như thế nào?*\nCác Quản lý trực tiếp vui lòng gửi thông tin đề xuất thăng chức, điều chuyển cho Phòng Nhân sự theo thông tin như sau:\n1. Kiều Huyền Phương (huyenphuong@telio.vn)\n2. Đặng Thị Thanh (dangthanh@telio.vn)\n3. Dương Thị Tuyết (duongtuyet@telio.vn)"
    ans2 = "*2. Thủ tục thăng chức nhân sự như thế nào?*\nCác Quản lý trực tiếp vui lòng gửi thông tin đề xuất thăng chức, điều chuyển cho Phòng Nhân sự theo thông tin như sau:\n1. Kiều Huyền Phương (huyenphuong@telio.vn)\n2. Đặng Thị Thanh (dangthanh@telio.vn)\n3. Dương Thị Tuyết (duongtuyet@telio.vn)"
    ans3 = "*3. Thông tin đề xuất thăng chức, điều chuyển thông tin cho ai?*\nCác Quản lý trực tiếp vui lòng gửi thông tin đề xuất thăng chức, điều chuyển cho Phòng Nhân sự theo thông tin như sau:\n1. Kiều Huyền Phương (huyenphuong@telio.vn)\n2. Đặng Thị Thanh (dangthanh@telio.vn)\n3. Dương Thị Tuyết (duongtuyet@telio.vn)"

class insurance_answer:
    ans1 = "*1. Danh mục các bệnh viện được đăng ký khám chữa bệnh?*\nĐể xem Danh mục các bệnh viện được đăng ký KCB bạn vui lòng xem tại đây. Lưu ý chỉ chọn các bệnh viện còn chỉ tiêu đăng ký\n<https://telio.1office.vn/document-company/list?folder_id=272|Danh mục nơi KCB>"
    ans2 = "*2. Khám bệnh thì được hưởng BHYT như thế nào?*\nTrường hợp khám chữa bệnh đúng tuyến: '100%' chi phí KCB\nTrường hợp khám chữa bệnh trái tuyến:\n- Tại bệnh viện tuyến trung ương là '40%' chi phí điều trị nội trú;\n- Tại bệnh viện tuyến tỉnh là '100%' chi phí điều trị nội trú;\n- Tại bệnh viện tuyến huyện là '100%' chi phí KCB."
    ans3 = "*3. Thủ tục và quyền lợi khi hưởng chế độ thai sản?*\nBạn vui lòng xem điều kiện, quyền lợi và thủ tục hưởng chế độ BHXH link dưới đây.\n<https://telio.1office.vn/document-company/list?folder_id=272|Thủ tục và quyền lợi BHXH>"
    ans4 = "*4. Thủ tục và quyền lợi khi hưởng chế độ dưỡng sức sau thai sản và dưỡng sức phục hồi sức khỏe sau ốm đau?*\nBạn vui lòng xem điều kiện, quyền lợi và thủ tục hưởng chế độ BHXH link dưới đây.\n<https://telio.1office.vn/document-company/list?folder_id=272|Thủ tục và quyền lợi BHXH>"
    ans5 = "*5. Có thẻ BH tự nguyện hoặc thẻ BH theo hộ gia đình thì có phải tham gia BHYT ở Telio không?*\nThẻ BHYT tự nguyện và thẻ BHYT theo hộ gia đình có thứ tự ưu tiên thấp hơn so với thẻ BHYT tại doanh nghiệp. Vì vậy khi tham gia BHYT tại Telio, bạn sẽ được cơ quan BHXH cấp thẻ BHYT, bạn cần làm thủ tục hoàn trả BHYT hộ gia đình/ BHYT tự nguyên, số tiền tương ứng với thời gian còn lại của thẻ BHYT sẽ được hoàn trả."
    ans6 = "*6. Tôi đã mua Bảo hiểm nhân thọ/ Bảo hiểm sức khỏe thì có cần tham gia BHYT tại Telio không?*\nBảo hiểm Nhân thọ/ Bảo hiểm sức khỏe không thuộc diện bảo hiểm bắt buộc và phạm vi bảo hiểm khác BHYT nên bạn có thể vừa tự mua Bảo hiểm Nhân thọ/ Bảo hiểm sức khỏe và tham gia BHYT tại Telio."
    ans7 = "*7. Đang ký HĐLĐ và tham gia Bảo hiểm xã hội tại công ty khác thì có tham gia Bảo hiểm xã hội tại Telio không?*\nTrường hợp bạn ký Hợp đồng lao động ở 2 công ty và đã tham gia Bảo hiểm xã hội tại công ty cũ, bạn không phải tham gia BHXH tại Telio nhưng công ty vẫn có trách nhiệm đóng BHTNLĐ - BNN ('0.5%' cho bạn), tuy nhiên bạn cần nộp một số giấy tờ sau chứng minh cho Telio:\n1. Ảnh chụp sổ BHXH\n2. Tờ xác nhận quá trình đóng BHXH ở đơn vị cũ do cơ quan BHXH cấp\n3. Giấy xác nhận không tham gia BHXH tại Telio."
    ans8 = "*8. Sai thông tin cá nhận trên sổ BHXH, thẻ BHYT thì có cần làm thủ tục thay đổi thông tin không?*\nTrường hợp sai thông tin cá nhân trên sổ BHXH, thẻ BHYT bạn cần liên hệ C&B để được hỗ trợ kê khai thay đổi, đồng thời nộp C&B các hồ sơ sau:\n1. Thẻ BHYT hoặc sổ BHXH cần thay đổi.\n2. Các giấy tờ pháp lý chứng minh/xác thực thông tin sai."
    ans9 = "*9. Thay đổi số CMTND hoặc căn cước công dân thì cần làm thủ tục thay đổi thông tin trên thẻ BHYT và sổ BHXH không?*\nBạn không cần thay đổi thông tin trên sổ BHXH và thẻ BHYT do cơ quan BHXH đã có dữ liệu đồng bộ."

class tax_answer:
    ans1 = "*1. Thủ tục đăng ký Người phụ thuộc?*\nBạn vui lòng nộp hồ sơ đăng ký NPT cho C&B trước 20 hàng tháng để được ghi nhận dữ liệu Giảm trừ gia cảnh trong tháng. Nếu sau ngày 20 của tháng, dữ liệu Giảm trừ gia cảnh sẽ được ghi nhận trong tháng tiếp theo.\nHồ sơ đăng ký NPT bạn vui lòng xem chi tiết tại link dưới đây.\nThông tin nộp hồ sơ:\nHN: Ms. Dương Tuyết (Email/Slack: tuyetduong@telio.vn)\nHCM: Ms. Nguyễn Thu (Email/Slack: nguyenthu1@telio.vn)\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=300|Link: Hướng dẫn đăng ký NPT>"
    ans2 = "*2. Tại sao khi ký HĐ thử việc hoặc hợp đồng đào tạo lại cần trích thuế TNCN 10%?*\nTheo quy định tại khoản 1 Điều 25 Thông tư 111:\nCác tổ chức, cá nhân trả tiền công, tiền thù lao, tiền chi khác cho cá nhân cư trú không ký hợp đồng lao động hoặc ký hợp đồng lao động dưới 03 tháng có tổng mức trả thu nhập từ 02 triệu đồng/lần trở lên thì phải khấu trừ thuế theo mức 10% trên thu nhập trước khi trả cho cá nhân…\nVì vậy đối với Hợp đồng thử việc và Hợp đồng đào tạo thuộc loại Hợp đồng dưới 3 tháng nên sẽ khấu trừ thuế 10% trên tổng thu nhập nếu mức thu nhập từ 2 triệu đồng/tháng.\nĐối với trường hợp này, nếu cuối năm bạn không thuộc đối tượng ủy quyền QTT công ty sẽ xuất chứng từ thuế TNCN để các bạn có thể đi Quyết toán thuế với cơ quan thuế để được hoàn lại tiền thuế TNCN nếu nộp thừa thuế trong năm. Nếu bạn thuộc đối tượng ủy quyền QTT cho Telio, công ty sẽ thực hiện QTT cho bạn và hoàn thuế nếu bạn được hoàn theo quy định."
    ans3 = "*3. Có từ 2 mã số thuế trở lên, cần làm thủ tục gì để gộp MST?*\nBạn vui lòng mang chứng minh thư lên cơ quan thuế quản lý công ty hiện tại  (với Telio do Chi cục thuế Quận Đống Đa quản lý) làm việc hoặc nếu không còn làm việc tại công ty nào bạn lên cơ quan thuế nơi đăng ký thường trú để được hướng dẫn để làm thủ tục gộp MST và chấm dứt hiệu lực hưởng của MST đăng ký sau."
    ans4 = "*4. Thay đổi số CMTND có cần thay đổi thông tin trên MST hay không?*\nKhi thay đổi số CMTND hoặc CCCD, bạn cần chuẩn bị các giấy tờ sau và nộp cho cơ quan thuế quản lý công ty hiện tại làm việc (với Telio do Chi cục thuế Quận Đống Đa quản lý) hoặc nếu không còn làm việc tại công ty nào bạn lên cơ quan thuế nơi đăng ký thường trú:\n- Tờ khai điều chỉnh, bổ sung thông tin đăng ký thuế (mẫu số 08-MST ban hành kèm theo Thông tư 105/2020/TT-BTC);\n- Bản sao các giấy tờ có thay đổi thông tin liên quan đến đăng ký thuế của cá nhân;"
    ans5 = "*5. Thủ tục tự Quyết toán thuế tại cơ quan thuế như thế nào?*\nCác bạn vui lòng truy cập vào link sau để xem hướng dẫn.\n<https://thuvienphapluat.vn/tintuc/vn/thoi-su-phap-luat-binh-luan-gop-y/34935/huong-dan-ca-nhan-tu-quyet-toan-thue-tncn-online|Thư viện pháp luật>"
    ans6 = "*6. Nếu muốn kiểm tra số thuế thừa hay thiếu trong năm để đi quyết toán thuế, tôi tra cứu như thế nào?*\nBạn vui lòng làm theo hướng dẫn tại file\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=303|Hướng dẫn tự tính số thuế thừa thiếu sau QTT>"

class salary_answer:
    ans1 = "*1. Quy định hiện tại về chấm công?*\nBạn vui lòng xem quy trình, quy định chấm công tại Link dưới đây.\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=270|Quy trình, Quy định chấm công>"
    ans2 = "*2. Các đối tượng được tự động/miễn chấm công*\nCác cấp từ Manager (Trưởng phòng/ Trưởng bộ phận) trở lên thì được tự động chấm công, tuy nhiên khi phát sinh các loại ngày nghỉ thì vẫn cần tạo đơn theo quy định công ty."
    ans3 = "*3. Hướng dẫn tạo các loại đơn trên 1 Office*\nBạn vui lòng xem Video hướng dẫn tạo đơn trên 1 Office tại link sau.\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=270|Hướng dẫn tạo đơn>"
    ans4 = "*4. Trường hợp nghỉ việc để chăm con ốm thông thường, không có giấy ra viện hoặc giấy chứng nhận nghỉ việc hưởng BHXH thì có được tạo đơn nghỉ con ốm hay không hay tạo đơn gì?*\nĐối với trường hợp này bạn tạo đơn nghỉ phép nếu còn phép tồn hoặc tạo đơn nghỉ Không lương nếu đã hết hạn mức phép. Đơn nghỉ con ốm chỉ dành cho các trường hợp nghỉ việc chăm con ốm nằm viện có Giấy ra viện hoặc Giấy chứng nhận nghỉ việc hưởng BHXH."
    ans5 = "*5. Trường hợp nghỉ ốm thông thường, không có giấy ra viện hoặc giấy chứng nhận nghỉ việc hưởng BHXH thì có được tạo đơn nghỉ ốm hay không hay tạo đơn gì?*\nĐối với trường hợp này bạn tạo đơn nghỉ phép nếu còn phép tồn hoặc tạo đơn nghỉ Không lương nếu đã hết hạn mức phép. Đơn nghỉ ốm chỉ dành cho các trường hợp nghỉ ốm nằm viện có Giấy ra viện hoặc Giấy chứng nhận nghỉ việc hưởng BHXH."
    ans6 = "*6. Trường hợp quá hạn 5 ngày không tạo đơn được, có thể có phương án nào để được tạo đơn bổ sung những ngày đó không?*\nTheo quy định hiện hành của công ty đã truyền thông và áp dụng từ T3/2021, chỉ được tạo đơn trong vòng 5 ngày kể từ ngày phát sinh đơn từ, trường hợp không tạo đơn đúng hạn, bạn sẽ không được ghi nhận công cho những ngày chưa tạo đơn."
    ans7 = "*7. Nếu muốn xem số ngày phép tồn đến thời điểm hiện tại thì làm như thế nào?*\nBạn đăng nhập vào tài khoản 1 Office, vào mục Chấm công,  di chuột đến mục thông tin phép, số phép tồn là cột Tổng tồn trong bảng."
    ans8 = "*8. Bản thân kết hôn thì được hưởng những quyền lợi gì?*\nNếu bạn kết hôn sẽ được hưởng các quyền lợi sau đây:\n1. Nghỉ việc hưởng lương 03 ngày kết hôn theo Luật lao động hiện hành\n2. Được tiền quà 2,000,000 VNĐ từ công ty cho các CBNV đã ký Hợp đồng chính thức hoặc Cộng tác viên/Dịch vụ đã làm việc trong công ty từ 06 tháng trở lên"
    ans9 = "*9. Bản thân sinh con (Lao động nữ) hoặc Vợ sinh con (Lao động nam) thì được hưởng những quyền lợi gì?*\nNếu bản thân sinh con hoặc vợ sinh con bạn sẽ được hưởng các quyền lợi sau đây:\n1. Nghỉ thai sản (lao động nữ) hoặc Nghỉ vợ sinh (Lao động nam) theo quy định của Luật BHXH\n2. Được tiền quà 2,000,000 VNĐ chào đón thành viên mới từ công ty dành cho các CBNV đã ký Hợp đồng chính thức hoặc Cộng tác viên/Dịch vụ đã làm việc trong công ty từ 06 tháng trở lên"
    ans10 = "*10. Công ty có chế độ gì cho ngày sinh nhật không?*\nChế độ bạn được hưởng vào ngày sinh nhật như sau:\n1. Vào tháng sinh nhật , bạn được nghỉ 01 ngày có hưởng lương, không được bảo lưu cho các tháng tiếp theo.\n2. Được tiền quà 200,000 VNĐ từ công ty"
    ans11 = "*11. Nếu gia đình có người mất, công ty có phúc lợi gì không?*\nKhi Bố/mẹ/con/chồng (vợ) của Nhân viên mất, các quyền lợi được hưởng như sau:\n1. Nghỉ hưởng lương 03 ngày theo quy định của Luật Lao động\n2. Đối với CBNV đã ký Hợp đồng chính thức hoặc Cộng tác viên/Dịch vụ đã làm việc trong công ty từ 06 tháng trở lên, công ty có chi tiền phúng viếng 2,000,000 VNĐ"
    ans12 = "*12. Trường hợp nhân viên bị ốm đau, tai nạn, công ty có chế độ thăm hỏi gì không?*\nĐối với CBNV đã ký Hợp đồng chính thức hoặc Cộng tác viên/Dịch vụ đã làm việc trong công ty từ 06 tháng trở lên, Ốm đau từ 05 ngày trở lên/Cấp cứu đột xuất phải nằm viện (Có giấy viện), công ty chi số tiền thăm hỏi như sau:\n- Phải phẫu thuật: 1,000,000 VNĐ\n- Không phải phẫu thuật: 500,000 VNĐ"

class work_answer:
    ans1 = "*1. Khi có phát sinh về kỷ luật lao động cần liên hệ ai Phòng Nhân sự để được giải quyết?*\nBạn vui lòng liên hệ Mrs. Đặng Thanh - Phòng Nhân sự (Email/Slack: dangthanh@telio.vn)để được hướng dẫn và xử lý."
    ans2 = "*2. Quy trình xử lý kỷ luật như thế nào?*\nBạn vui lòng xem Quy trình và các Biểu mẫu xử lý kỷ luật tại Link sau.\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=275|Hướng dẫn xử lý kỷ luật>"
    ans3 = "*3. Muốn xem Nội quy lao động thì cần xem ở đâu?*\nBạn vui lòng xem nội quy lao động tại link sau:\n<https://telio.1office.vn/document-company/list?tab=all&folder_id=312|Nội quy lao động>"
    

